version: "3.8"
services:

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fastapi_app
    volumes:
      - .:/app
    command: bash -c " alembic upgrade head && uvicorn app.main:app  --host 0.0.0.0 --reload"
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
      - "3000:3000"
    links:
      - db:db
    depends_on:
      - db

  db:
    restart: always
    image: postgres:15-alpine
    container_name: db_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env-docker

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
