version: "3.8"
services:

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fastapi_app
    volumes:
      - .:/app
    command: uvicorn app.main:app  --host 0.0.0.0 --reload
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
      - "3000:3000"
    links:
      - db:db
    depends_on:
      - db


  db:
    restart: always
    image: postgres:15-alpine
    container_name: db_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env-docker

volumes:
  postgres_data:
