version: "3.8"
services:

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fastapi_app
    volumes:
      - .:/app
    command: uvicorn app.main:app  --host 0.0.0.0 --reload
    ports:
      - 8008:8000
    depends_on:
      - db


  db:
    image: postgres
    container_name: db_app
    ports:
      - "5432:5432"
    env_file:
      - .env-docker
    