"""adding user to email

Revision ID: 0afe550fd73c
Revises: ade405f5fd94
Create Date: 2024-09-04 14:39:31.901832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afe550fd73c'
down_revision = 'ade405f5fd94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_emails', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'temp_emails', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temp_emails', type_='foreignkey')
    op.drop_column('temp_emails', 'user_id')
    # ### end Alembic commands ###
