"""application_name

Revision ID: 610906eaeff4
Revises: 2981198ebd93
Create Date: 2024-05-21 10:05:07.781389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610906eaeff4'
down_revision = '2981198ebd93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('application_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'application_name')
    # ### end Alembic commands ###
