"""first_migrations2

Revision ID: a1a2a196bd38
Revises: a651625d0bdb
Create Date: 2023-07-18 20:20:00.730703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a2a196bd38'
down_revision = 'a651625d0bdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
