"""Not nullable values, added cascade deletion

Revision ID: abca2d58dcc0
Revises: f7d52b31a846
Create Date: 2023-08-08 11:46:48.550543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abca2d58dcc0"
down_revision = "f7d52b31a846"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "applications", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "applications", "website_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("categories", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "categories", "temp_email_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "categories", "category_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("message_types", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "message_types", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "messages", "application_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "messages", "message_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("messages", "topic", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "messages", "message_text", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("roles", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("roles", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("temp_emails", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "temp_emails", "access_token", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "role_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "user_token", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "user_token", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "role_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "temp_emails", "access_token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("temp_emails", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("roles", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("roles", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "messages", "message_text", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("messages", "topic", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "messages", "message_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "messages", "application_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "message_types", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("message_types", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "categories", "category_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "categories", "temp_email_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("categories", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "applications", "website_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "applications", "category_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
