"""Added unique constraints, removed temp_email access token

Revision ID: c7402d600dfa
Revises: fe6bb73ad1f5
Create Date: 2023-10-23 09:23:40.946445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7402d600dfa"
down_revision = "fe6bb73ad1f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "applications", ["category_id", "website_url"])
    op.create_unique_constraint(None, "categories", ["user_id", "temp_email_id"])
    op.create_unique_constraint(
        None, "messages", ["application_id", "message_text", "topic"]
    )
    op.drop_constraint("temp_emails_access_token_key", "temp_emails", type_="unique")
    op.drop_column("temp_emails", "access_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "temp_emails",
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        "temp_emails_access_token_key", "temp_emails", ["access_token"]
    )
    op.drop_constraint(None, "messages", type_="unique")
    op.drop_constraint(None, "categories", type_="unique")
    op.drop_constraint(None, "applications", type_="unique")
    # ### end Alembic commands ###
