"""OauthAccount update

Revision ID: d1863b7ee853
Revises: ac5174394a27
Create Date: 2023-10-21 17:51:36.054093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1863b7ee853'
down_revision = 'ac5174394a27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
