"""On delete cascade fix

Revision ID: fe6bb73ad1f5
Revises: abca2d58dcc0
Create Date: 2023-08-14 14:39:56.998029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe6bb73ad1f5"
down_revision = "abca2d58dcc0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "applications_category_id_fkey", "applications", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "applications", "categories", ["category_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("categories_user_id_fkey", "categories", type_="foreignkey")
    op.create_foreign_key(
        None, "categories", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("messages_application_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        None, "messages", "applications", ["application_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("users_role_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "roles", ["role_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key("users_role_id_fkey", "users", "roles", ["role_id"], ["id"])
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_application_id_fkey",
        "messages",
        "applications",
        ["application_id"],
        ["id"],
    )
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.create_foreign_key(
        "categories_user_id_fkey", "categories", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.create_foreign_key(
        "applications_category_id_fkey",
        "applications",
        "categories",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###
