name: Integration-test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: ["main"]

jobs:
  pre-deploy-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Myosotis-backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docker/requirements/base.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r docker/requirements/base.txt
      

      - name: Run tests
        if: success() || failure()
        run: |
          export $(grep -v '^#' docker/test/env/.integration-test| xargs)
          pytest -v -s --cov-report xml --cov . --html=report.html --self-contained-html --alluredir=tests/allure-results
        env:
          DISPLAY: ":99"
        
      - name: Coverage report
        if: success() || failure()
        uses: 5monkeys/cobertura-action@v13
        with:
          minimum_coverage: 25

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: report.html
          retention-days: 5
      
      - name: Get Allure history # Step to retrieve Allure history
        uses: actions/checkout@v3
        if: success() || failure()
        continue-on-error: true # Continue execution even if the step fails
        with:
          ref: testing-result-pages # Specify the branch to retrieve Allure history from
          path: testing-result-pages # Set the destination path for Allure history

      - name: Allure report action # Step to generate Allure report
        uses: simple-elf/allure-report-action@master
        if: success() || failure()
        with:
          allure_results: tests/allure-results
          allure_report: tests/allure-report
          allure_history: allure-history 
          report_url: https://meek-florentine-a03d43.netlify.app
          keep_reports: 20 # Specify the number of previous reports to keep
      
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=allure-history --functions=functions
        env:
          NETLIFY_SITE_ID:  56288579-1cf4-478f-bfe4-73a565df2f0c
          NETLIFY_AUTH_TOKEN: nfp_se4DT28bsNY1k7Fc7UgYhUQF4Z5cZJWceaa4

      - name: Deploy report to testing-result-pages branch
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: testing-result-pages
          PUBLISH_DIR: allure-history
