name: Project Issue State Sync

on: 
  schedule:
    # At minute 0 every 2 hours
    - cron:  24 * * * *
  
  workflow_dispatch:
    # Manual trigger

jobs:
  issue-state-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync issue states
        uses: dasmerlon/project-issue-state-sync@v2
        with:
          github_token: ${{ secrets.BOARD }}
          owner: ZinnurovArtur
          project_number: 1
          closed_statuses: Ready for deployment
          open_statuses: In Progress
