name: Project Issue State Sync

on:
  project_card:
    types: [created, edited, moved]

  workflow_dispatch:
    # Manual trigger

jobs:
  issue-state-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync issue states
        uses: dasmerlon/project-issue-state-sync@v2
        with:
          github_token: ${{ secrets.BOARD }}
          owner: ZinnurovArtur
          project_number: 2
          closed_statuses: Ready for deployment
          open_statuses: In progress
